### ISSUE TITLE
HashStore 1.1.0 Release

### ISSUE THREAD

**Issue by doulikecookiedough** [DataONEorg/hashstore#133]
Prepare HashStore for 1.1.0 Release:
- [x] Update pyproject.toml version number
- Review test coverage
    - [x] Reasonably ensure every method has a pytest & accurate docstrings
    - [x] Re-organize pytests (there doesn't need to be so many modules)
- [x] Review documentation & docstrings for accuracy
- [ ] Update README.md with citation (date, DOI)
- [x] Utilize poetry bump for changing version numbers
    - [Add version info to hashstore lib](https://github.com/DataONEorg/hashstore/issues/136)
- [x] Add type hints to method signatures
    - [Add type hints](https://github.com/DataONEorg/hashstore/issues/137)
- [x] [Use path libs for constructing paths & clean-up pathing code](https://github.com/DataONEorg/hashstore/issues/139)
- [ ] [Use module name in logging](https://github.com/DataONEorg/hashstore/issues/140)
- [x] [Use a lib for constructing yaml](https://github.com/DataONEorg/hashstore/issues/138)
    - If too time intensive, defer to next minor release

**Comment by doulikecookiedough** [comment]
This has been completed via [HashStore 1.1.0 Release](https://github.com/DataONEorg/hashstore/pull/84)
